name: Wiki backup
on:
  schedule:
    - cron:  '51 23 * * *'
  gollum:
  
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Backup wiki
        uses: Mine02C4/auto_backup_wiki_action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: wiki
